name: CI/CD React App Local

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout Helm chart
        uses: actions/checkout@v3
        with:
          repository: ebrizha/env-app-test
          path: helm-chart

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || echo "No lint script"

      - name: Run tests
        run: npm test -- --watchAll=false --silent

      - name: Build React app
        run: npm run build

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          docker build -t ebrizha/react-app-test:${{ github.sha }} \
                       -t ebrizha/react-app-test:latest .

      - name: Push image
        run: |
          docker push ebrizha/react-app-test:${{ github.sha }}
          docker push ebrizha/react-app-test:latest

      - name: Deploy with Helm
        run: |
          helm upgrade --install app ./helm-chart/app-chart \
            --set frontend.image.tag=${{ github.sha }} \
            --set frontend.image.pullPolicy=Always \
            --reuse-values \
            --rollback-on-failure \
            --timeout 5m
