name: CI/CD React App Local

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || echo "No lint script"

      - name: Run tests
        run: npm test -- --watchAll=false --silent

      - name: Build React app
        run: npm run build

      - name: Setup Docker for Minikube
        run: eval $(minikube -p minikube docker-env)

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ebrizha/react-app-test:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ebrizha/react-app-test:${{ github.sha }}

      - name: Inject image tag into deployment
        run: |
          sed -i '' "s|IMAGE_TAG|${{ github.sha }}|g" _k8s/deployment.yaml

      - name: Deploy to Minikube
        run: |
          kubectl apply -f _k8s/deployment.yaml
          kubectl apply -f _k8s/service.yaml
          kubectl apply -f _k8s/ingress.yaml
          kubectl rollout status deployment/react-app-test
